### ISSUE TITLE
Adopting CSD for existing CalConnect public documents

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-csd#11]
CalConnect maintains a public document repository, of which most documents can be re-published in the new CSD or a CSD-derived format.

http://www.calconnect.org/resources/documents/document-register

The existing document types are:

* ARTF=Code Artifact
* PRES=Presentation
* PROP=Proposal
* RCMD=Recommendation
* REPT=Report
* REVW=Public Review
* IETF DRAFT=IETF Internet Draft
* IETF RFC=IETF Pubished Standard

The existing document numbering scheme is "CD YYSS", where:

* "CD" stands for "CalConnect document
* "YY" is the last two digits of a YYYY year
* "SS" is a sequential unique number for the documents published within that YY year

Metadata of a document looks like this:

```
CALCONNECT DOCUMENT CD 1705
Type:      Report
Title:     Report on CalConnect Conference XL
Version:   1.0
Date:      2017-10-23
Status:    Published
Source:    N/A
```

**Comment by ronaldtse** [comment]
The only gap is that we need to have a list of document types and document statuses we support.

1. Amend the CSD model to accept these
2. Update asciidoctor-csd to accept these

**Comment by opoudjis** [comment]
You have not provided in the foregoing a list of statuses, nor does the CalConnect list. The statuses you had provided did not include "published".

**Comment by opoudjis** [comment]
I've added the doctypes to the schema and the Readme. No code modifications needed to process them.

Need confirmation on statuses.

**Comment by ronaldtse** [comment]
For doctypes, I think we only need to do this:

* PROP=Proposal => This is actually just a "draft"
* RCMD=Recommendation => This is a "standard"
* REPT=Report => This is a new doctype.

For "published" we should just use "publishedAt" using bibliographic dates?

**Comment by opoudjis** [comment]
Does including the other types do any harm though?

publishedAt is not a document status. Your statuses were `working-draft`,
`committee-draft`, `draft-standard`, `standard`, `obsolete`.

**Comment by ronaldtse** [comment]
Probably no harm done. What's your suggestion regarding `published`?

**Comment by opoudjis** [comment]
I think replace "standard" as a status with "published"; after all, it's problematic to apply the status "standard" to a published recommendation or report.

**Comment by ronaldtse** [comment]
Agreed. Let's replace "standard" with "published". Documents that are "standards" presumably will have a doctype that includes the phrase "standard" anyway.

**Comment by opoudjis** [comment]
Working Draft and Committee Draft are still neuter. Could you call the Draft Standard stage a Prepublication Draft?

**Comment by opoudjis** [comment]
Your call.

**Comment by ronaldtse** [comment]
Let’s say we remove the “standard” word from the statuses. Then can we align isodoc with this new set? Or will isodoc still use its specific terms separately? Or maybe we should “standardize the document statuses” across everything.

**Comment by ronaldtse** [comment]
Two of the the latest docs are provided here: https://github.com/riboseinc/csd-public-documents

**Comment by opoudjis** [comment]
... My opinion, fwiw, is that ISO's stages should not be treated as universal defaults (in Standoc), because they are too complicated, and because too many standards in the world do not use them; better to have loose defaults. But I gather you want ISO doc statuses (stage and substage) done for CSD; please confirm?

**Comment by ronaldtse** [comment]
Basically an ISO document has 7 stages (stage is good enough, no need substage):
1. Proposal
2. Working draft
3. Committee draft
4. Draft standard
5. Final draft
6. Published
7. Withdrawn

W3C uses these 5 stages:

1. Working draft
2. Candidate recommendation
3. Proposed recommendation
4. W3C recommendation
5. Rescinded recommendation

IETF:

1. Internet-Draft
2. Workgroup draft
3. Published
4. Obsolete

OASIS:

1. Proposal
2. Working draft
3. Committee draft
4. Committee specification
5. OASIS Standard
6. Retracted

OMG:

1. Proposal
2. Beta
3. Formal

(can't find out the rest about OMG specifications, all stage 2/3 are accompanied by versions like 1.0, 1.1, 2.0...)

Probably better to go the ISO way since most national standards (for sure GB does) probably align to these 7 stages. Thoughts?

**Comment by opoudjis** [comment]
Ideally in fact you want a superset of all of these for a generic standard. But as it turns out, ISO is a superset of most of the others, but for the clash between Obsolete and Withdrawn, and the vagueness of W3C's Proposed Recommendation. So I will use the ISO stages as you've reworded them here in standoc.

Ideally also we would use the same stages across all standards, with well defined mappings—except that I am reluctant to drop the ISO numbers, that will just confuse people, since we're retaining ISO substages.

**Comment by opoudjis** [comment]
I've put these in standoc; do you want them in CSD?

**Comment by ronaldtse** [comment]
Yes please, that would be fantastic in CSD too. Thanks!

**Comment by opoudjis** [comment]
Have introduced new colours for the new statuses. So:

Proposal: light blue
Working-Draft: orange
Committee-Draft: pink
Draft-Standard: yellow
Final-Draft: burnt red
Published: green
Withdrawn: grey
