### ISSUE TITLE
Mismatches with csd-style styling

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-csd#12]
Differences noted in RED.

Screenshot of https://github.com/riboseinc/csd-style:
<img width="1165" alt="screen shot 2018-04-14 at 5 58 56 pm" src="https://user-images.githubusercontent.com/11865/38767057-d8ec5f9e-400d-11e8-9aa6-1f53b0051e39.png">

Screenshot of generated CSD document:
<img width="1167" alt="screen shot 2018-04-14 at 5 59 49 pm" src="https://user-images.githubusercontent.com/11865/38767055-d79ea91c-400d-11e8-8e0e-4c67098d881c.png">

**Comment by ronaldtse** [comment]
Hmm... Is this fixed? I can't see the updated styling...

This is a re-created published document:

https://github.com/riboseinc/csd-public-documents/blob/master/conference41rpt/csd-report-conference-41.adoc

* It is not a draft, but has draft styling (showing the draft block)
* It shows two "XXX"s at the status
* On the sidebar bottom it shows "CALCONNECT" but not "CALCONNECT REPORT" as it should have been

**Comment by opoudjis** [comment]
... Nope. I just made it locally, and it has none of these problems.

**Comment by opoudjis** [comment]
@ronaldtse, can I close this?

**Comment by ronaldtse** [comment]
@opoudjis yes, just confirmed the style is good. Are we dropping the "dots" though? The generated one has no dots.

We could replace the dots with something like this:
https://stackoverflow.com/questions/13607117/css-css3-pixelate-dot-background

Maybe @pierrefortier could confirm.

**Comment by opoudjis** [comment]
I had dropped the dots because I was uncomfortable with file dependencies for the output. It is perfectly doable, but it's just one more dependency that people will forget about when they're moving CSD outputs around. I'll do it if you insist, but if we can avoid it, let's avoid it.
