### ISSUE TITLE
List numbered and unnumbered bullets all missing in HTML

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-csd#19]
Everything looks like without a bullet?

<img width="691" alt="screen shot 2018-04-22 at 9 52 24 pm" src="https://user-images.githubusercontent.com/11865/39095714-7a570f0e-4677-11e8-8274-99ab2af159f5.png">

**Comment by opoudjis** [comment]
Yes, that's in the stylesheet Pierre wrote!

````
ol, ul {
  list-style: none; }
````

I'm disabling that.

**Comment by ronaldtse** [comment]
Cool, let me just confirm the bullet styling are as they should be.
