### ISSUE TITLE
Bundle with asciidoctor 1.5.7 fails to run

### ISSUE THREAD

**Issue by PeterTKY** [riboseinc/asciidoctor-csd#20]
I'm getting this error when building CSD documents:

```
NoMethodError: undefined method `asciidoc_sub' for #<Asciidoctor::Csd::Converter:0x00007fa889891000>
gems/asciidoctor-csd-41b173a7ed94/lib/asciidoctor/csd/converter.rb:44:in `block (2 levels) in title'
```

This seems to be an incompatibility with the newly released asciidoctor 1.5.7?

Thanks!

**Comment by ronaldtse** [comment]
Thanks @PeterTKY  for reporting. 

@opoudjis could you help a look at this? Thanks!

**Comment by opoudjis** [comment]
@PeterTKY: no. This is a new function just introduced into asciidoctor-iso, which asciidoctor-csd is a subclass off. Please run `bundle update`.

**Comment by ronaldtse** [comment]
@opoudjis @PeterTKY the latest asciidoctor-csd apparently requires the newest asciidoctor-iso (0.7.5), I've updated the gems now; this issue is resolved.
