### ISSUE TITLE
Issues with HTML output

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-csd#21]
1. Annex should not be unrendered?

<img width="785" alt="screen shot 2018-05-04 at 11 01 58 am" src="https://user-images.githubusercontent.com/11865/39611487-9629908c-4f8a-11e8-812a-944446cdeced.png">

2. Annex title should be in single line

<img width="261" alt="screen shot 2018-05-04 at 11 01 21 am" src="https://user-images.githubusercontent.com/11865/39611498-9f95f5d4-4f8a-11e8-8ac8-5fcf090a8d4b.png">

3. Reference numbering, title, year should not be bolded. (probably?)

<img width="791" alt="screen shot 2018-05-04 at 11 01 09 am" src="https://user-images.githubusercontent.com/11865/39611501-adf609e8-4f8a-11e8-8061-f802b5b8a593.png">

**Comment by opoudjis** [comment]
Annex title now in single line

**Comment by opoudjis** [comment]
3. Bolding is in the CSS for Biblio class. Removing.

**Comment by opoudjis** [comment]
All documents in the gem family require any appendixes to precede the bibliography in the asciidoc source, in order to be recognised at all. I can fix that in code so that ordering of appendixes and bibliography is arbitrary, so long as they are after the main body of sections; or I can leave this as a rule. Because the rule works (and is in place in the exemplars), I am treating resolving this as an enhancement (lower priority).

**Comment by ronaldtse** [comment]
I think we should fix it in code because it's hard to remember that rule (we have to either learn to read the README everytime or succumb to errors the code throws)

**Comment by ronaldtse** [comment]
@opoudjis is this fixed? Thanks!

**Comment by opoudjis** [comment]
1-2 are fixed. 3 is not yet done, and I've demoted it in priority to an enhancement.

**Comment by ronaldtse** [comment]
The current HTML generated is a bit off (e.g. the title margins) compared to the current csd-style.

**Comment by opoudjis** [comment]
@ronaldtse: The CSS was copied from https://github.com/riboseinc/csd-style/blob/master/csd-operator-guidelines.html, which is the updated instance of CSS that Pierre worked on, in response to https://github.com/riboseinc/csd-style/issues/11.  The behaviour with long margins is identical in the two. So I don't see what needs to be done here; I'll need more specifics.

**Comment by ronaldtse** [comment]
@opoudjis I confirm that the latest version has the title margins fixed. Is there anything left here? 3?

**Comment by opoudjis** [comment]
That was permitting appendixes/annexes to occur after the final bibliography. In fact, I've just fixed that in asciidoctor-iso. So no, this is done.
