### ISSUE TITLE
Incompatible with Relaton?

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-csd#31]
```
bundler: failed to load command: metanorma (/Users/myself/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bin/metanorma)
NoMethodError: undefined method `save_cache_biblio' for #<Asciidoctor::Csd::Converter:0x00007fe9b602fb50>
  /Users/myself/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/asciidoctor-csd-0.4.1/lib/asciidoctor/csd/converter.rb:79:in `makexml'
```

**Comment by opoudjis** [comment]
I found this issue yesterday, and pushed version 0.4.2 of the gem to address it. Please bundle update and confirm if the issue is still there.

**Comment by ronaldtse** [comment]
Yes, maybe the gem hasn't been released?

**Comment by ronaldtse** [comment]
It's still 0.4.1 on Rubygems : https://rubygems.org/gems/asciidoctor-csd

<img width="713" alt="screen shot 2018-07-08 at 4 33 12 pm" src="https://user-images.githubusercontent.com/11865/42418133-a5c2caac-82cc-11e8-968d-962fc4649086.png">

**Comment by ronaldtse** [comment]
Gem released and fixed. Thanks @opoudjis !
