### ISSUE TITLE
Need example spec

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-csd#4]
Need an example standard for this. @ronaldtse, if you can't supply a plausible CSD standard, I'll use the Rice document.

**Comment by ronaldtse** [comment]
@opoudjis apologies for the delay. We can use https://tools.ietf.org/html/rfc6350 as a sample document.

**Comment by opoudjis** [comment]
Long task of tweaking markup.

**Comment by opoudjis** [comment]
Have started this
