### ISSUE TITLE
Convert two existing internet-drafts for exemplary usage

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-csd#5]
As title.

**Comment by opoudjis** [comment]
Douglass has been converted to Asciidoc-RFC

Path is:

Douglass.RFC > Douglass.AsciidocRFC  (done)
IcalRelations.RFC > IcalRelations.AsciidocRFC
Douglass.AsciidocRFC > Douglass.AsciidocCSD
IcalRelations.AsciidocRFC > IcalRelations.AsciidocCSD

**Comment by opoudjis** [comment]
AsciidocRFC done for both

**Comment by opoudjis** [comment]
Douglass converted to CSD that will compile into documents.

I will be doing just enough to compile these, and then turning to the long list of bugs and validation errors. The work is basically converting the RFCXML bibliographies at a first cut, and working out what to do with the ascii art.

**Comment by opoudjis** [comment]
Converted IcalRelations as well.

Allowed Ascii Art in figures in CSD.

**Comment by opoudjis** [comment]
Questions back to you, @ronaldtse:

* ISO Standards have mandatory, boilerplate-heavy forewords. Should CSD? If so, I'll need sample text for the exemplars.

* Do you want the ISO rules about decimals? Including that decimal point should be avoided in favour of decimal comma?
* Do you care about what kinds of references are normative?

**Comment by ronaldtse** [comment]
* ISO Standards has boilerplate, and CSD should also have boilerplate for legal issues. But I don't have the text now.

* I think they are rather specific with ISO, I don't think we care about that in CSD.

* Yes, CSD will need to differentiate normative references from informative ones.

1. Speaking of RFC XML bibliographies -- it brings back a suggestion I made before about making a gem. Now, in fact, we should transform RFC bibliography into RfcBibliographicItem!

2. Question: any model updates we need to do -- and could you do it?

**Comment by opoudjis** [comment]
There are plenty of needed updates for the RFC biblio model. I can do the model updates. I will not work on asciidoc-bibliography—as I've said, I need to constrain what I work on.

**Comment by opoudjis** [comment]
Need to fix RFC as well

**Comment by opoudjis** [comment]
RFC fixed. There is no foreword currently; once you supply it, you can add it to the CSD documents.
