### ISSUE TITLE
Key words like "MUST", "MUST NOT" should be tagged in CSD / CSD-HTML

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-csd#7]
From https://github.com/riboseinc/csd-style/issues/1

They're just text and not tagged right now. Maybe we should give them some element in order to style them?

**Comment by opoudjis** [comment]
As I asked in that ticket: bp14 markup like in asciidoctor-rfc, or something more generic?

**Comment by ronaldtse** [comment]
Something more generic. Maybe call them “keyword” or “requirement” in csd xml, and “em” in html?

**Comment by opoudjis** [comment]
keyword. I'll introduce `[keyword]#...#`, which will make to `<span class="keyword">...</span>`. (You don't want to make it `<em>`, that's already `_..._`.)
